# langage du test
language: python
# Pour éviter que Travis n'installe des choses inutiles aux tests
sudo:false
# version
python:
  - 3.8
# on lance le script de test
script:
  - python3 app/tests/tests.py
# notifications par email
notifications:
  email:
    recipients:
      - victor.meynaud@chartes.psl.eu
    on_success: always
    on_failure: always

