# langage du test
language: python
# version
python:
  - 3.8
# on lance le script de test
script:
  - python3 tests_ic/tests.py
  - pytest --count=500 -v -s test_unitaire.py
# notifications par email
notifications:
  email:
    recipients:
      - victor.meynaud@chartes.psl.eu
    on_success: never
    on_failure: always

