# langage du test
language: python
# Travis installe par défaut les requirements. Cette syntaxe permet de l'éviter car c'est inutile
# dans notre cas
install: pip --version
# version
python:
  - 3.8
# on lance le script de test
script:
  - python3 app/tests/tests.py
# notifications par email
notifications:
  email:
    recipients:
      - victor.meynaud@chartes.psl.eu
    on_success: always
    on_failure: always

