liste_pays = ["Afghanistan", "Afrique du Sud", "Åland, Îles", "Albanie", "Algérie", "Allemagne", "Andorre",
    "Angola", "Anguilla", "Antarctique", "Antigua et Barbuda", "Antilles néerlandaises", "Arabie Saoudite", "Argentine",
    "Arménie", "Aruba", "Australie", "Autriche", "Azerbaïdjan", "Bahamas", "Bahrein", "Bangladesh", "Barbade", "Bélarus",
    "Belgique", "Bélize", "Bénin", "Bermudes", "Bhoutan", "Bolivie (État plurinational de)",
    "Bonaire, Saint-Eustache et Saba", "Bosnie-Herzégovine", "Botswana", "Bouvet, Ile", "Brésil", "Brunéi Darussalam",
    "Bulgarie", "Burkina Faso", "Burundi", "Cabo Verde", "Caïmans, Iles", "Cambodge", "Cameroun", "Canada", "Chili",
    "Chine", "Christmas, île", "Chypre", "Cocos/Keeling (Îles)", "Colombie", "Comores", "Congo",
    "Congo, République démocratique du", "Cook, Iles", "Corée, République de",
    "Corée, République populaire démocratique de", "Costa Rica", "Côte d'Ivoire", "Croatie", "Cuba",
    "Curaçao", "Danemark", "Djibouti", "Dominicaine, République", "Dominique", "Egypte", "El Salvador",
    "Emirats arabes unis", "Equateur", "Erythrée", "Espagne", "Estonie", "Etats-Unis d'Amérique", "Ethiopie",
    "Falkland/Malouines (Îles)", "Féroé, îles", "Fidji", "Finlande", "France", "Gabon", "Gambie", "Géorgie",
    "Géorgie du sud et les îles Sandwich du sud", "Ghana", "Gibraltar", "Grèce", "Grenade", "Groenland", "Guadeloupe",
    "Guam", "Guatemala", "Guernesey", "Guinée", "Guinée-Bissau", "Guinée équatoriale", "Guyana", "Guyane française",
    "Haïti", "Heard, Ile et MacDonald, îles", "Honduras", "Hong Kong", "Hongrie", "Île de Man",
    "Îles mineures éloignées des Etats-Unis", "Îles vierges britanniques", "Îles vierges des Etats-Unis",
    "Inde", "Indien (Territoire britannique de l'océan)", "Indonésie", "Iran, République islamique d'", "Iraq",
    "Irlande", "Islande", "Israël", "Italie", "Jamaïque", "Japon", "Jersey", "Jordanie", "Kazakhstan", "Kenya",
    "Kirghizistan", "Kiribati", "Koweït", "Lao, République démocratique populaire", "Lesotho", "Lettonie", "Liban",
    "Libéria", "Libye", "Liechtenstein", "Lituanie", "Luxembourg", "Macao", "Macédoine du nord", "Madagascar",
    "Malaisie", "Malawi", "Maldives", "Mali", "Malte", "Mariannes du nord, Iles", "Maroc", "Marshall, Iles", "Martinique",
    "Maurice", "Mauritanie", "Mayotte", "Mexique", "Micronésie, Etats Fédérés de", "Moldova, République de", "Monaco",
    "Mongolie", "Monténégro", "Montserrat", "Mozambique", "Myanmar", "Namibie", "Nauru", "Népal", "Nicaragua", "Niger",
    "Nigéria", "Niue", "Norfolk, Ile", "Norvège", "Nouvelle-Calédonie", "Nouvelle-Zélande", "Oman", "Ouganda",
    "Ouzbékistan", "Pakistan", "Palaos", "Palestine, Etat de", "Panama", "Papouasie-Nouvelle-Guinée", "Paraguay",
    "Pays-Bas", "Pays inconnu", "Pays multiples", "Pérou", "Philippines", "Pitcairn", "Pologne", "Polynésie française",
    "Porto Rico", "Portugal", "Qatar", "République arabe syrienne", "République centrafricaine", "Réunion", "Roumanie",
    "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord", "Russie, Fédération de", "Rwanda", "Sahara occidental",
    "Saint-Barthélemy", "Saint-Kitts-et-Nevis", "Saint-Marin", "Saint-Martin (partie française)",
    "Saint-Martin (partie néerlandaise)", "Saint-Pierre-et-Miquelon", "Saint-Siège", "Saint-Vincent-et-les-Grenadines",
    "Sainte-Hélène, Ascension et Tristan da Cunha", "Sainte-Lucie", "Salomon, Iles", "Samoa", "Samoa américaines",
    "Sao Tomé-et-Principe", "Sénégal", "Serbie", "Seychelles", "Sierra Leone", "Singapour", "Slovaquie", "Slovénie",
    "Somalie", "Soudan", "Soudan du Sud", "Sri Lanka", "Suède", "Suisse", "Suriname", "Svalbard et île Jan Mayen",
    "Swaziland", "Tadjikistan", "Taïwan, Province de Chine", "Tanzanie, République unie de", "Tchad", "Tchécoslovaquie",
    "Tchèque, République", "Terres australes françaises", "Thaïlande", "Timor-Leste", "Togo", "Tokelau", "Tonga",
    "Trinité-et-Tobago", "Tunisie", "Turkménistan", "Turks-et-Caïcos (Îles)", "Turquie", "Tuvalu", "Ukraine", "URSS",
    "Uruguay", "Vanuatu", "Vatican", "Venezuela (République bolivarienne du)", "Viet Nam", "Viet Nam (Sud)",
    "Wallis et Futuna", "Yémen", "Yougoslavie", "Zaïre", "Zambie", "Zimbabwe"]

liste_villes = ["Kaboul", "Pretoria", "Cape Town", "Johannesburg", "Tirana", "Alger", "Annaba", "Oran",
    "Berlin", "Düsseldorf", "Francfort", "Hambourg", "Munich", "Sarrebruck", "Stuttgart", "Andorre-la-Vieille",
    "Luanda", "Castries", "Djeddah", "Riyad", "Buenos Aires", "Erevan", "Canberra", "Sydney", "Vienne",
    "Bakou", "Panama", "Manama", "Dacca", "Bruxelles", "Guatemala", "Cotonou", "New Delhi", "Calcutta",
    "Minsk", "Rangoun", "La Paz", "Sarajevo", "Gaborone", "Recife", "Rio de Janeiro",
    "São Paulo", "Brasilia", "Sofia", "Ouagadougou", " Ouagadougou", "Bujumbura", "Phnom Penh",
    "Yaoundé", "Douala", "Ottawa", "Montréal", "Québec", "Toronto", "Vancouver", "Moncton", "Santiago",
    "Shanghai", "Shenyang", "Hong Kong", "Wuhan", "Beijing", "Chengdu", "Canton", "Nicosie", "Bogotá",
    "Bogota", "Moroni", "Brazzaville", "Pointe-Noire", "Séoul", "San José", "Abidjan", "Zagreb",
    "La Havane", "Copenhague", "Djibouti", "Le Caire", "Mancheya - Alexandrie", "Abou Dabi", "Dubaï", "Quito",
    "Asmara", "Madrid", "Barcelone", "Bilbao", "Tallinn", "Atlanta", "Boston", "Chicago",
    "Houston", "New Orleans", "Los Angeles", "Miami", "New York", "San Francisco", "Washington",
    "Addis Abeba", "Helsinki", "Libreville", "Dakar", "Brufut", "Tbilissi", "Accra", "Athènes",
    "Thessalonique", " Athènes", "Guatemala ciudad", "Conakry", "Malabo", "Bissao", "Paramaribo",
    "Port-au-Prince", "Tegucigalpa", " Budapest", "Wellington", "Suva", "Port-Vila", "Mumbai",
    "Pondichéry", "Bangalore", "Jakarta", "Bagdad", "Erbil", "Téhéran", "Dublin", "Reykjavik", "Tel-Aviv",
    "Haïfa", "Jérusalem", "Rome", "Naples", "Milan", "Kingston", "Tokyo", "Kyoto", "Amman", "Nour-Soultan",
    "Almaty", "Nairobi", "Bichkek", "Pristina", "Koweït", "Vientiane", "Riga", "Beyrouth", "Monrovia",
    "Tripoli", "Vilnius", "Luxembourg", "Skopje", "Antananarivo", "Kuala Lumpur", "Colombo", "Bamako",
    "La Valette", "Rabat - Chellah", "Agadir", "Casablanca", "Marrakech", "Tanger", "Fès", "Rabat",
    "Port-Louis", "Nouakchott", "Mexico", "Chisinau", "Monaco", "Oulan Bator", "Podgorica", "Maputo",
    "Windhoek", "Katmandou", "Managua", "Niamey", "Abuja", "Lagos", "Oslo", "Mascate", "Kampala",
    "Tachkent", "Islamabad", "Karachi", "Port Moresby", "Asunción", "La Haye", "Amsterdam", "Lima",
    "Makati city", "Manille", "Varsovie", "Cracovie", "Lisbonne", "Doha", "Bangui", "Kinshasa",
    "Saint-Domingue", "Prague", "Bucarest", "Londres", "Edimbourg", "Moscou", "Ekaterinbourg",
    "Saint-Pétersbourg", "Kigali", "San Salvador", "Belgrade", "Mahé", "Singapour", "Bratislava", "Ljubljana",
    "Khartoum", "Djouba", "Stockholm", "Berne", "Zurich", "Genève", "Damas", "Douchanbé", "Taipei",
    "Dar es Salaam ", "N'Djamena", "Bangkok", "Lomé", "Port d'Espagne", "Tunis", "Achgabat", "Ankara",
    "Istanbul", "Kiev", "Montevideo", "Caracas", "Hanoï", "Ho Chi-Minh Ville", "Lusaka", "Harare"]